server:
  port: 20002
spring:
  application:
    name: service
eureka:
  client:
    service-url:
      defaultZone: http://ivfzhoudebian:10001/eureka,http://ivfzhoudebian:10002/eureka,http://ivfzhoudebian:10003/eureka
  instance:
    prefer-ip-address: true
