server:
  port: 10003
spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://ivfzhoudebian:10001/eureka,http://ivfzhoudebian:10002/eureka
