server:
  port: 10009
spring:
  application:
    name: feign
  cloud:
    openfeign:
      httpclient:
        max-connections: 200
        max-connections-per-route: 50
      client:
        config:
          default: # 表示全局配置。
            connectTimeout: 1000 # 连接超时（毫秒）。
            readTimeout: 1000 # 读取超时（毫秒）。
            loggerLevel: FULL # 日志级别。
          service: # 对应 @FeignClient(name="service")
            connectTimeout: 3000
            readTimeout: 5000
            loggerLevel: BASIC
      compression:
        request:
          enabled: true
          mime-types: text/xml,application/xml,application/json
          min-request-size: 2048
        response:
          enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://ivfzhoudebian:10001/eureka,http://ivfzhoudebian:10002/eureka,http://ivfzhoudebian:10003/eureka
