server:
  port: 30001
spring:
  application:
    name: feign
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/,http://127.0.0.1:10002/eureka/,http://127.0.0.1:10003/eureka/
feign: #配置feign超时后，ribbon的配置会失效。
  hystrix:
    enabled: true #开起feign熔断功能,Feign中的Hystrix功能默认关闭
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 5000
        MaxAutoRetries: 0
        MaxAutoRetriesNextServer: 0
      service: #指定服务配置
        connectTimeout: 1000
        readTimeout: 1000
        MaxAutoRetries: 0
        MaxAutoRetriesNextServer: 0

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD #资源隔离，默认线程池隔离，信号量隔离SEMAPHORE。
          thread:
            timeoutInMilliseconds: 1000 #默认1秒
        timeout:
          enabled: true #默认true，如果为false，feign的超时还有用
      circuitBreaker: #熔断器配置，默认打开
        enabled: true
        requestVolumeThreshold: 5 #单位时间内失败次数，默认20，超过次数熔断
        sleepWindowInMilliseconds: 5000 #多久进入半开状态，默认5秒
