spring:
  redis:
    cluster:
      max-redirects: 5 #连接失败最大重连次数
      nodes:
        - 192.168.14.199:6379
        - 192.168.14.199:6380
        - 192.168.14.199:6381
        - 192.168.14.199:6382
        - 192.168.14.199:6383
        - 192.168.14.199:6384
    ## 连接超时时间（毫秒）
    timeout: 3000
    ## Redis数据库索引(默认为0)
    database: 0
    password: 123456
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
    #连接池的最大连接数，使用负数没有限制
    # jedis:
    #   pool:
    #     max-active: 100
    #     # 连接池的最大空闲连接
    #     max-idle: 10
    #     # 连接池的最大阻塞等待时间
    #     max-wait: 100000
    #     # 连接池中的最小空闲连接
    #     min-idle: 0
    #     enabled: true
server:
  port: 6565