spring:
  data:
    redis:
      cluster:
        max-redirects: 5 # 连接失败最大重连次数。
        nodes:
          - ivfzhoudockerredis1:6380
          - ivfzhoudockerredis2:6381
          - ivfzhoudockerredis3:6382
          - ivfzhoudockerredis4:6383
          - ivfzhoudockerredis5:6384
          - ivfzhoudockerredis6:6385
      ## 连接超时时间（毫秒）。
      timeout: 3000
      ## Redis 数据库索引（默认为 0）。
      database: 0
      password: 123456
      lettuce:
        pool:
          max-idle: 16
          max-active: 32
          min-idle: 1
          max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制。
server:
  port: 8080
