server:
  port: 30000
spring:
  application:
    name: ribbon
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/,http://127.0.0.1:10002/eureka/,http://127.0.0.1:10003/eureka/
ribbon:
  eureka:
    enabled: true # 开关ribbon
  ConnectTimeout: 1000 # 连接超时
  ReadTimeout: 6000 # 读超时
  MaxAutoRetries: 0 # 每个节点尝试次数。
  MaxAutoRetriesNextServer: 0 # 找集群下个服务的尝试次数，或者尝试同一台服务，默认1。次数等于（n+1）*(m+1)次。
service: # 配置负载均衡策略。
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule  # RandomRule指定为随机。
    #NFLoadBalancerPingClassName:
    #NIWSServerListClassName:
    #NIWSServerListFilterClassName:
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD # 资源隔离，默认线程池隔离，信号量隔离SEMAPHORE。
          thread:
            timeoutInMilliseconds: 5000 # 默认1秒
        timeout:
          enabled: true #默认true，如果为false，feign的超时还有用
      circuitBreaker: #熔断器配置，默认打开
        enabled: true #单位时间内失败次数，默认20，超过次数熔断
        requestVolumeThreshold: 5
        sleepWindowInMilliseconds: 5000 #多久进入半开状态，默认5秒
