server:
  port: 20003
spring:
  application:
    name: service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/,http://127.0.0.1:10002/eureka/,http://127.0.0.1:10003/eureka/
  instance:
    prefer-ip-address: true
