package cn.ivfzhou.java.mybatis.generator.dao;

import cn.ivfzhou.java.mybatis.generator.bean.Author;

public interface AuthorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_author
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_author
     *
     * @mbg.generated
     */
    int insert(Author record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_author
     *
     * @mbg.generated
     */
    int insertSelective(Author record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_author
     *
     * @mbg.generated
     */
    Author selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_author
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Author record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_author
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Author record);
}