server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /springboot
mybatis:
  type-aliases-package: cn.ivfzhou.java.springboot.bean
spring:
  application:
    name: springboot
  datasource:
    url: jdbc:mysql://ivfzhoudockermysql:3306/db_springboot
    username: ivfzhou
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ivfzhoudockerredis
      username:
      password: 123456
      jedis:
        pool:
          max-active: 8
          max-wait: 1
  thymeleaf:
    mode: HTML # LEGACYHTML5
    encoding: UTF-8
    cache: false
