server:
  port: 10004
spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes: # 配置路由规则。
            - id: feign
              uri: lb://feign
              predicates:
                - Path=/feign/**
              filters:
                - myFilter
                - StripPrefix=1 # # 移除路径中的第一段（如 /order），再将剩余部分转发给后端服务。
                - name: RequestRateLimiter
                  args:
                    key-resolver: '#{@remoteAddrKeyResolver}'
                    redis-rate-limiter.replenishRate: 1 # 每秒填充数。
                    redis-rate-limiter.burstCapacity: 1 # 最大容量。
                    redis-rate-limiter.requestedTokens: 1 # 最大容量。
  data:
    redis:
      host: ivfzhoudockerredis
      password: 123456
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    service-url:
      defaultZone: http://ivfzhoudebian:10001/eureka,http://ivfzhoudebian:10002/eureka,http://ivfzhoudebian:10003/eureka
