server:
  port: 10000
spring:
  application:
    name: zuul
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/,http://127.0.0.1:10002/eureka/,http://127.0.0.1:10003/eureka/
zuul:
  routes:
    client1:
      serviceId: feign
      path: /feign/** # http://127.0.0.1:10000/feign/feign
    client2:
      serviceId: ribbon
      path: /ribbon/**
