###
GET http://127.0.0.1:8080/springboot/render0


###
GET http://127.0.0.1:8080/springboot/render1


###
GET http://127.0.0.1:8080/springboot/render2


###
GET http://127.0.0.1:8080/springboot/render3?textual=hello
