###
GET http://ivfzhoudebian:8080/set/key/value


###
GET http://ivfzhoudebian:8080/get/key


###
POST http://ivfzhoudebian:8080/hset/key/hkey
Content-Type: application/json

{
  "name": "ivfzhou",
  "age": 18
}


###
GET http://ivfzhoudebian:8080/hget/key/hkey
