server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes: # 配置路由规则
        - id: feign
          uri: lb://feign
          predicates:
            - Path=/feign/**
          filters:
            - myFilter
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 1 # 每秒填充数
                redis-rate-limiter.burstCapacity: 1 # 最大容量
                redis-rate-limiter.requestedTokens: 1 # 最大容量
        - id: ribbon
          uri: lb://ribbon
          predicates:
            - Path=/ribbon/**
          filters:
            - StripPrefix=1
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/,http://127.0.0.1:10002/eureka/,http://127.0.0.1:10003/eureka/